config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#home'

  resources :lists, except: [:edit, :update] do # primary instance, has many movies and bookmarks # also only possible
    resources :bookmarks, only: [:new, :create] # we need only this
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, :list, presence: true
  validates :comment, length: {minimum: 6}, allow_blank: true
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  # has_many :movies, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # I need new and create and destroy

  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params # I can controll the input to the database, so i can;t do like user admit = true
    params.require(:bookmark).permit(:comment, :movie_id) # possible to manipulate just comment and movie id
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy] #

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new # this doesn't have to be here because of the before action, now the show runs twice of so
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<p>new bookmarks</p>


<div>
  <h3>Add a movie to your <%= @list.name %> list</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
    <%= f.association :movie, prompt: 'Select a movie'%>
    <%= f.submit%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<p>index</p>

    <h1>Save any kind of movies</h1>
      <h3>My Lists</h3>
    <%= link_to 'Create a movie list', new_list_path %>
  <div>
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
          <%= list.name %>
      <% end %>
    <% end %>
  </div>

app/views/lists/new.html.erb
<p>new lists</p>
  <h3>Create a new list</h3>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, placeholder: 'Drama' %>
    <%= f.submit%>
  <% end %>
</div>

app/views/lists/show.html.erb
<p>show</p>

<h1><%= @list.name %></h1>
<div>
  <%= link_to 'add a movie', new_list_bookmark_path(@list)%>
  <%= link_to 'detete this list', list_path(@list), method: :delete, data: { confirm: 'Are you sure you want to delete this list?' } %>
</div>
<% @list.movies.each do |movie| %>
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <%= image_tag movie.poster_url, alt: movie.title%>
    <%= movie.title %>
    <%= movie.overview %>
      <div>
        <%= bookmark.comment %>
      </div>
      <%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}%>
<% end %>
</div>